import { join } from "node:path"
import { expect, test } from "bun:test"
import { createSmartLockSystemJson } from "../../app/SmartLock/createSmartLockSystemJson"
import { formatProjectPdfExportedOn } from "../../components/OutputFiles/createProjectPdf"
import type { BomViewRow } from "../../lib/bom/types"
import { createPdf, type CreatePdfParams } from "../../lib/pdfgen/createPdf"
import { initResvgWasm } from "../../lib/pdfgen/svgRaster"

// Node has no bundler to emit the wasm asset URL, so initialize resvg-wasm
// from the binary shipped in node_modules before rendering.
const resvgWasmPath = Bun.resolveSync(
  "@resvg/resvg-wasm/index_bg.wasm",
  import.meta.dir,
)
await initResvgWasm(await Bun.file(resvgWasmPath).arrayBuffer())

const drv8876SchematicSheetSvg = await Bun.file(
  join(
    import.meta.dir,
    "fixtures",
    "DRV8876-driver-pwm-operation-ph-en.circuit-schematic-simulation.snap.svg",
  ),
).text()
const circuitToSvgSchematicSheetSvg = await Bun.file(
  join(import.meta.dir, "fixtures", "schematic-sheet.snap.svg"),
).text()
const exampleExportedAt = new Date("2026-07-02T04:13:00.000Z")
const exampleExportedOn = formatProjectPdfExportedOn(exampleExportedAt)

const bomRows: BomViewRow[] = [
  {
    referenceDesignators: "U1",
    manufacturer: "Texas Instruments",
    mpn: "CC2340R5",
    packageName: "QFN-32",
    value: "2.4 GHz MCU",
    quantity: "1",
    functionalBlock: "BLE Module",
    partName: "Wireless MCU",
    description: "Wireless MCU, 2.4 GHz, BLE",
    lifecycle: "Active",
    unitPrice: "2.84 USD",
    stock: "18,500",
  },
  {
    referenceDesignators: "U2",
    manufacturer: "Texas Instruments",
    mpn: "BQ25155",
    packageName: "WCSP-25",
    value: "PMIC",
    quantity: "1",
    functionalBlock: "PMIC",
    partName: "Battery charger and power path controller",
    description: "Battery charger, power-path controller, PMIC",
    lifecycle: "Active",
    unitPrice: "1.67 USD",
    stock: "6,200",
  },
  {
    referenceDesignators: "U3, U4",
    manufacturer: "Texas Instruments",
    mpn: "TCA39306",
    packageName: "WQFN-16",
    value: "Level translator",
    quantity: "2",
    functionalBlock: "Signal-level Shift, Radio Transceiver",
    partName: "Dual-supply voltage-level translator",
    description: "Dual-supply, voltage-level translator, low-voltage logic",
    lifecycle: "Active",
    unitPrice: "0.48 USD",
    stock: "24,100",
  },
]

const examplePdf: CreatePdfParams = {
  titlePage: {
    type: "title",
    projectName: "Smart Lock (UWB Smart Lock)",
    subtitle: "Project document",
    description:
      "Reference package generated from the system block designer PDF generator.",
    preparedFor: "Product Engineering",
    preparedBy: "Unknown Author",
    date: exampleExportedOn,
    revision: "A",
  },
  projectDetailsPage: {
    type: "project_details",
    title: "PROJECT DETAILS",
    headerLabel: "System Block Designer",
    projectName: "Smart Lock (UWB Smart Lock)",
    entries: [
      {
        label: "Project name",
        value: "Smart Lock (UWB Smart Lock)",
      },
      {
        label: "Functionality(s)",
        value: "Communication, Memory, Processing & Security, Power",
      },
      {
        label: "Application(s)",
        value: "Security",
      },
      {
        label: "Selected CAD tool",
        value: "System Block Designer",
      },
      {
        label: "Generated by",
        value: "Unknown Author",
      },
      {
        label: "Exported on",
        value: exampleExportedOn,
      },
    ],
    disclaimer:
      "Project title, description, and block diagram content may be AI-generated. Schematics, BOM, and resolved components are derived from the current design export.",
  },
  technicalSpecificationsPage: {
    type: "technical_specifications",
    summary: "Initial electrical and integration targets.",
    rows: [
      {
        name: "Connectivity",
        value: "UWB / BLE / NFC",
        notes: "Supports proximity, mobile unlock, and commissioning flows.",
      },
      {
        name: "Host",
        value: "BLE Module",
        notes: "Coordinates radio, flash, authentication, and PMIC control.",
      },
      {
        name: "Power",
        value: "PMIC",
        notes: "Supplies regulated rails to the application electronics.",
      },
      {
        name: "External Interfaces",
        value: "SPI / I2C / GPIO",
        notes: "Shown in the generated system architecture page.",
      },
    ],
  },
  bomPage: {
    type: "bom",
    rows: bomRows,
  },
  systemArchitecturePage: {
    type: "system_architecture",
    subtitle: "Generated from the smart-lock system JSON fixture.",
    systemJson: createSmartLockSystemJson(),
  },
  schematicSheetSvgs: [
    {
      type: "schematic_sheet",
      title: "Schematics - DRV8876 Driver PWM Operation",
      svg: drv8876SchematicSheetSvg,
    },
    {
      type: "schematic_sheet",
      title: "Schematics - Circuit Sheet",
      svg: circuitToSvgSchematicSheetSvg,
    },
  ],
}

test("snapshots each page of example01 as png", async () => {
  const pdfBytes = await createPdf(examplePdf)
  await expect(pdfBytes).toMatchPdfSnapshot(import.meta.path)
}, 15_000)

test("createPdf sanitizes unsupported BOM glyphs instead of throwing", async () => {
  const pdfBytes = await createPdf({
    bomPage: {
      type: "bom",
      rows: [
        {
          referenceDesignators: "U1",
          manufacturer: "Texas Instruments",
          mpn: "ABC123",
          packageName: "QFN-32",
          value: "母板",
          quantity: "1",
          functionalBlock: "Control",
          partName: "母 board controller",
          description: "母 board controller, custom control logic",
          lifecycle: "Active",
          unitPrice: "1.00 USD",
          stock: "100",
        },
      ],
    },
  })

  expect(pdfBytes).toBeInstanceOf(Uint8Array)
  expect(pdfBytes.byteLength).toBeGreaterThan(0)
})
