import { convertCircuitJsonToSchematicSvg } from "circuit-to-svg"
import type { BomViewRow } from "../../lib/bom/types"
import { LIBRARY } from "../../lib/design-system/library"
import { type CreatePdfParams, createPdf } from "../../lib/pdfgen/createPdf"
import type { CircuitJson } from "../../lib/system-blocks/resolveSystemJsonToCircuitJson"
import type {
  SystemBlock,
  SystemConnection,
  SystemDiagram,
  SystemJson,
} from "../../lib/system-json/system-json"

const DEFAULT_PROJECT_NAME = "System Block Design"
const DEFAULT_GENERATED_BY = "Unknown Author"
const DEFAULT_CAD_TOOL = "System Block Designer"
const DEFAULT_HEADER_LABEL = "System Block Designer"
const DEFAULT_EXPORT_TIME_ZONE = "America/Los_Angeles"
const DEFAULT_DISCLAIMER =
  "Project title, description, and block diagram content may be AI-generated. Schematics, BOM, and resolved components are derived from the current design export."
const FUNCTIONALITY_CATEGORY_ORDER = LIBRARY.map((category) => category.name)
const FUNCTIONALITY_CATEGORY_LOOKUP = new Map(
  FUNCTIONALITY_CATEGORY_ORDER.map((category) => [
    toCategoryKey(category),
    category,
  ]),
)

interface BuildProjectPdfOptions {
  exportedAt?: Date
}

function getProjectName(systemJson: SystemJson[]): string {
  const diagram = systemJson.find(
    (item): item is SystemDiagram => item.type === "system_diagram",
  )
  return diagram?.name?.trim() || DEFAULT_PROJECT_NAME
}

export function getProjectFileName(systemJson: SystemJson[]): string {
  const slug = getProjectName(systemJson)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
  return slug || "system-block-design"
}

/**
 * Maps the designer's system JSON (and optionally resolved circuit JSON) onto
 * the pdfgen page inputs. The schematic sheet is only included when circuit
 * JSON is available, so the PDF still generates from system JSON alone.
 */
export function buildProjectPdfParams(
  systemJson: SystemJson[],
  circuitJson: CircuitJson | null,
  bomRows: BomViewRow[] = [],
  options: BuildProjectPdfOptions = {},
): CreatePdfParams {
  const diagram = systemJson.find(
    (item): item is SystemDiagram => item.type === "system_diagram",
  )
  const blocks = systemJson.filter(
    (item): item is SystemBlock => item.type === "system_block",
  )
  const connections = systemJson.filter(
    (item): item is SystemConnection => item.type === "system_connection",
  )
  const projectName = getProjectName(systemJson)
  const functionality = deriveFunctionalityList(blocks)
  const applications = deriveApplicationList(
    projectName,
    functionality,
    diagram?.description,
  )
  const exportedOn = formatProjectPdfExportedOn(
    options.exportedAt ?? new Date(),
  )

  const params: CreatePdfParams = {
    titlePage: {
      type: "title",
      projectName,
      subtitle: "Project document",
      description:
        diagram?.description ??
        "Generated from the system block designer, covering the project overview, system architecture, schematic sheets, and BOM.",
      preparedBy: DEFAULT_GENERATED_BY,
      date: exportedOn,
    },
    projectDetailsPage: {
      type: "project_details",
      title: "PROJECT DETAILS",
      headerLabel: DEFAULT_HEADER_LABEL,
      projectName,
      entries: [
        {
          label: "Project name",
          value: projectName,
        },
        {
          label: "Functionality(s)",
          value: functionality,
        },
        {
          label: "Application(s)",
          value: applications,
        },
        {
          label: "Selected CAD tool",
          value: DEFAULT_CAD_TOOL,
        },
        {
          label: "Generated by",
          value: DEFAULT_GENERATED_BY,
        },
        {
          label: "Exported on",
          value: exportedOn,
        },
      ],
      disclaimer: DEFAULT_DISCLAIMER,
    },
    technicalSpecificationsPage: {
      type: "technical_specifications",
      summary: "Functional blocks defined in the system design.",
      rows: blocks.map((block) => ({
        name: block.label ?? block.system_block_id,
        value: block.category.join(", ") || "—",
        notes: block.description,
      })),
    },
    systemArchitecturePage: {
      type: "system_architecture",
      subtitle: `${blocks.length} blocks, ${connections.length} connections`,
      systemJson,
    },
    bomPage: {
      type: "bom",
      rows: bomRows,
    },
  }

  if (circuitJson && circuitJson.length > 0) {
    const schematicSvg = convertCircuitJsonToSchematicSvg(
      circuitJson as Parameters<typeof convertCircuitJsonToSchematicSvg>[0],
    )
    params.schematicSheetSvgs = [
      {
        type: "schematic_sheet",
        title: `Schematics - ${projectName}`,
        svg: schematicSvg,
      },
    ]
  }

  return params
}

export async function createProjectPdf(
  systemJson: SystemJson[],
  circuitJson: CircuitJson | null,
  bomRows: BomViewRow[] = [],
): Promise<Uint8Array<ArrayBuffer>> {
  const bytes = await createPdf(
    buildProjectPdfParams(systemJson, circuitJson, bomRows),
  )
  // pdf-lib types its output as Uint8Array<ArrayBufferLike>; normalize to an
  // owned ArrayBuffer-backed view so the bytes are a valid Blob part.
  return new Uint8Array(bytes)
}

function deriveFunctionalityList(blocks: SystemBlock[]) {
  const detected = new Set<string>()
  const extras: string[] = []

  for (const block of blocks) {
    const category = normalizeFunctionalityCategory(
      block.category[0] ?? block.label?.trim(),
    )
    if (!category || detected.has(category)) continue

    detected.add(category)
    if (!FUNCTIONALITY_CATEGORY_LOOKUP.has(toCategoryKey(category))) {
      extras.push(category)
    }
  }

  const ordered = [
    ...FUNCTIONALITY_CATEGORY_ORDER.filter((category) =>
      detected.has(category),
    ),
    ...extras,
  ]

  if (ordered.length > 0) return ordered.join(", ")

  return Array.from(
    new Set(
      blocks
        .map((block) => block.label?.trim())
        .filter((label): label is string => Boolean(label)),
    ),
  ).join(", ")
}

function deriveApplicationList(
  projectName: string,
  functionality: string,
  description?: string,
) {
  const haystack = `${projectName} ${description ?? ""} ${functionality}`

  if (/lock|secure|security|access|auth/i.test(haystack)) {
    return "Security"
  }
  if (/automotive|vehicle/i.test(haystack)) {
    return "Automotive"
  }
  if (/wearable|consumer|mobile|home/i.test(haystack)) {
    return "Connected Devices"
  }
  return "Embedded Systems"
}

export function formatProjectPdfExportedOn(date: Date) {
  const parts = new Intl.DateTimeFormat("en-US", {
    day: "numeric",
    month: "long",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
    timeZoneName: "short",
    timeZone: DEFAULT_EXPORT_TIME_ZONE,
  }).formatToParts(date)

  return `${getDateTimePart(parts, "day")} ${getDateTimePart(parts, "month")} ${getDateTimePart(parts, "year")}, ${getDateTimePart(parts, "hour")}:${getDateTimePart(parts, "minute")} ${getDateTimePart(parts, "timeZoneName")}`
}

function normalizeFunctionalityCategory(category?: string) {
  if (!category) return undefined

  const trimmedCategory = category.trim()
  if (!trimmedCategory) return undefined

  const exactMatch = FUNCTIONALITY_CATEGORY_LOOKUP.get(
    toCategoryKey(trimmedCategory),
  )
  if (exactMatch) return exactMatch

  const singularMatch = FUNCTIONALITY_CATEGORY_LOOKUP.get(
    toCategoryKey(trimmedCategory.replace(/s\b/i, "")),
  )
  if (singularMatch) return singularMatch

  return trimmedCategory
}

function toCategoryKey(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
}

function getDateTimePart(
  parts: Intl.DateTimeFormatPart[],
  type: Intl.DateTimeFormatPartTypes,
) {
  return parts.find((part) => part.type === type)?.value ?? ""
}
