import type { AnyCircuitElement, SchematicSheet } from "circuit-json"
import { convertCircuitJsonToSchematicSvg } from "circuit-to-svg"
import type { BomViewRow } from "../../lib/bom/types"
import { LIBRARY } from "../../lib/design-system/library"
import { type CreatePdfParams, createPdf } from "../../lib/pdfgen/createPdf"
import type { CircuitJson } from "../../lib/system-blocks/resolveSystemJsonToCircuitJson"
import type {
  SystemBlock,
  SystemConnection,
  SystemDiagram,
  SystemJson,
} from "../../lib/system-json/system-json"
import { formatProjectPdfExportedOn } from "./formatProjectPdfExportedOn"

const DEFAULT_PROJECT_NAME = "System Block Design"
const DEFAULT_GENERATED_BY = "Unknown Author"
const DEFAULT_CAD_TOOL = "System Block Designer"
const DEFAULT_HEADER_LABEL = "System Block Designer"
const DEFAULT_DISCLAIMER =
  "Project Title, Project Description, and Block Diagram may be AI-Generated. Schematics, BOM, and Components are not AI-Generated."
const FUNCTIONALITY_CATEGORY_ORDER = LIBRARY.map((category) => category.name)
const FUNCTIONALITY_CATEGORY_LOOKUP = new Map(
  FUNCTIONALITY_CATEGORY_ORDER.map((category) => [
    toCategoryKey(category),
    category,
  ]),
)

interface BuildProjectPdfOptions {
  exportedAt?: Date
}

// Render each schematic sheet SVG at an A4-landscape aspect ratio (297:210) so the
// sheet frame circuit-to-svg draws fills the page instead of being letterboxed.
const SHEET_SVG_WIDTH = 1400
const SHEET_SVG_HEIGHT = Math.round((SHEET_SVG_WIDTH * 210) / 297)

function getSchematicSheets(circuitJson: CircuitJson): SchematicSheet[] {
  return (circuitJson as AnyCircuitElement[])
    .filter(
      (element): element is SchematicSheet =>
        element.type === "schematic_sheet",
    )
    .slice()
    .sort((a, b) => (a.sheet_index ?? 0) - (b.sheet_index ?? 0))
}

function getProjectName(systemJson: SystemJson[]): string {
  const diagram = systemJson.find(
    (item): item is SystemDiagram => item.type === "system_diagram",
  )
  return diagram?.name?.trim() || DEFAULT_PROJECT_NAME
}

export function getProjectFileName(systemJson: SystemJson[]): string {
  const slug = getProjectName(systemJson)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "")
  return slug || "system-block-design"
}

/**
 * Maps the designer's system JSON (and optionally resolved circuit JSON) onto
 * the pdfgen page inputs. The schematic sheet is only included when circuit
 * JSON is available, so the PDF still generates from system JSON alone.
 */
export function buildProjectPdfParams(
  systemJson: SystemJson[],
  circuitJson: CircuitJson | null,
  bomRows: BomViewRow[] = [],
  options: BuildProjectPdfOptions = {},
): CreatePdfParams {
  const diagram = systemJson.find(
    (item): item is SystemDiagram => item.type === "system_diagram",
  )
  const blocks = systemJson.filter(
    (item): item is SystemBlock => item.type === "system_block",
  )
  const connections = systemJson.filter(
    (item): item is SystemConnection => item.type === "system_connection",
  )
  const projectName = getProjectName(systemJson)
  const functionality = deriveFunctionalityList(blocks)
  const applications = deriveApplicationList(
    projectName,
    functionality,
    diagram?.description,
  )
  const exportedOn = formatProjectPdfExportedOn(
    options.exportedAt ?? new Date(),
  )

  const params: CreatePdfParams = {
    titlePage: {
      type: "title",
      projectName,
      subtitle: "Project document",
      description:
        diagram?.description ??
        "Generated from the system block designer, covering the project overview, system architecture, schematic sheets, and BOM.",
      preparedBy: DEFAULT_GENERATED_BY,
      date: exportedOn,
    },
    projectDetailsPage: {
      type: "project_details",
      title: "PROJECT DETAILS",
      headerLabel: DEFAULT_HEADER_LABEL,
      projectName,
      entries: [
        {
          label: "Project name",
          value: projectName,
        },
        {
          label: "Functionality(s)",
          value: functionality,
        },
        {
          label: "Application(s)",
          value: applications,
        },
        {
          label: "Selected CAD tool",
          value: DEFAULT_CAD_TOOL,
        },
        {
          label: "Generated by",
          value: DEFAULT_GENERATED_BY,
        },
        {
          label: "Exported on",
          value: exportedOn,
        },
      ],
      disclaimer: DEFAULT_DISCLAIMER,
    },
    technicalSpecificationsPage: {
      type: "technical_specifications",
      summary: "Functional blocks defined in the system design.",
      rows: blocks.map((block) => ({
        name: block.label ?? block.system_block_id,
        value: block.category.join(", ") || "—",
        notes: block.description,
      })),
    },
    systemArchitecturePage: {
      type: "system_architecture",
      subtitle: `${blocks.length} blocks, ${connections.length} connections`,
      systemJson,
    },
    bomPage: {
      type: "bom",
      rows: bomRows,
    },
  }

  if (circuitJson && circuitJson.length > 0) {
    const circuit = circuitJson as Parameters<
      typeof convertCircuitJsonToSchematicSvg
    >[0]
    const sheets = getSchematicSheets(circuitJson)

    if (sheets.length > 0) {
      // One PDF page per schematic sheet, rendered with circuit-to-svg's native
      // sheet frame (no hand-drawn frame). Cross-sheet connections appear as net
      // labels on each sheet.
      params.schematicSheetSvgs = sheets.map((sheet) => ({
        type: "schematic_sheet",
        // core sets display_name (from the block label) but it is missing from
        // circuit-json's exported SchematicSheet type, so read it the same way
        // circuit-to-svg's own stacked-sheet renderer does.
        title:
          (sheet as { display_name?: string }).display_name ??
          sheet.name ??
          `Schematics - ${projectName}`,
        svg: convertCircuitJsonToSchematicSvg(circuit, {
          schematicSheetId: sheet.schematic_sheet_id,
          width: SHEET_SVG_WIDTH,
          height: SHEET_SVG_HEIGHT,
        }),
      }))
    } else {
      // No explicit sheets: fall back to a single schematic page.
      params.schematicSheetSvgs = [
        {
          type: "schematic_sheet",
          title: `Schematics - ${projectName}`,
          svg: convertCircuitJsonToSchematicSvg(circuit),
        },
      ]
    }
  }

  return params
}

export async function createProjectPdf(
  systemJson: SystemJson[],
  circuitJson: CircuitJson | null,
  bomRows: BomViewRow[] = [],
): Promise<Uint8Array<ArrayBuffer>> {
  const bytes = await createPdf(
    buildProjectPdfParams(systemJson, circuitJson, bomRows),
  )
  // pdf-lib types its output as Uint8Array<ArrayBufferLike>; normalize to an
  // owned ArrayBuffer-backed view so the bytes are a valid Blob part.
  return new Uint8Array(bytes)
}

function deriveFunctionalityList(blocks: SystemBlock[]) {
  const detected = new Set<string>()
  const extras: string[] = []

  for (const block of blocks) {
    const category = normalizeFunctionalityCategory(
      block.category[0] ?? block.label?.trim(),
    )
    if (!category || detected.has(category)) continue

    detected.add(category)
    if (!FUNCTIONALITY_CATEGORY_LOOKUP.has(toCategoryKey(category))) {
      extras.push(category)
    }
  }

  const ordered = [
    ...FUNCTIONALITY_CATEGORY_ORDER.filter((category) =>
      detected.has(category),
    ),
    ...extras,
  ]

  if (ordered.length > 0) return ordered.join(", ")

  return Array.from(
    new Set(
      blocks
        .map((block) => block.label?.trim())
        .filter((label): label is string => Boolean(label)),
    ),
  ).join(", ")
}

function deriveApplicationList(
  projectName: string,
  functionality: string,
  description?: string,
) {
  const haystack = `${projectName} ${description ?? ""} ${functionality}`

  if (/lock|secure|security|access|auth/i.test(haystack)) {
    return "Security"
  }
  if (/automotive|vehicle/i.test(haystack)) {
    return "Automotive"
  }
  if (/wearable|consumer|mobile|home/i.test(haystack)) {
    return "Connected Devices"
  }
  return "Embedded Systems"
}

function normalizeFunctionalityCategory(category?: string) {
  if (!category) return undefined

  const trimmedCategory = category.trim()
  if (!trimmedCategory) return undefined

  const exactMatch = FUNCTIONALITY_CATEGORY_LOOKUP.get(
    toCategoryKey(trimmedCategory),
  )
  if (exactMatch) return exactMatch

  const singularMatch = FUNCTIONALITY_CATEGORY_LOOKUP.get(
    toCategoryKey(trimmedCategory.replace(/s\b/i, "")),
  )
  if (singularMatch) return singularMatch

  return trimmedCategory
}

function toCategoryKey(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, " ")
    .trim()
}
